# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentinel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentinel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esentinel.proto\x12\x08sentinel\"s\n\x12TransactionRequest\x12\x0f\n\x07tx_hash\x18\x01 \x01(\t\x12\x16\n\x0esender_pqc_key\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"E\n\x0eRiskAssessment\x12\x0f\n\x07is_safe\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t2Z\n\nAiSentinel\x12L\n\x12\x41nalyzeTransaction\x12\x1c.sentinel.TransactionRequest\x1a\x18.sentinel.RiskAssessmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentinel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=28
  _globals['_TRANSACTIONREQUEST']._serialized_end=143
  _globals['_RISKASSESSMENT']._serialized_start=145
  _globals['_RISKASSESSMENT']._serialized_end=214
  _globals['_AISENTINEL']._serialized_start=216
  _globals['_AISENTINEL']._serialized_end=306
# @@protoc_insertion_point(module_scope)
